services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fx-rates-local-postgres
    environment:
      POSTGRES_USER: local_db_fx_rates1
      POSTGRES_PASSWORD: local_db_fx_rates1
      POSTGRES_DB: DATABASE1
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local_db_fx_rates -d DATABASE"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  postgres_data:
