// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Currency struct {
	IsoCode   string
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type CurrencyCoverage struct {
	ProviderKey string
	IsoCode     string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
}

type Provider struct {
	Key           string
	Name          string
	CountryCode   *string
	RateType      *string
	PivotCurrency *string
	DataUrl       *string
	TermsUrl      *string
	PublishTime   *int32
	PublishDays   *string
	CoverageStart pgtype.Date
}

type Rate struct {
	Date     pgtype.Date
	Base     string
	Quote    string
	Rate     float64
	Provider string
}

type SyncRun struct {
	ID           int64
	Provider     string
	Mode         string
	Status       string
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	RowsFetched  int32
	RowsInserted int32
	RowsSkipped  int32
	ErrorMessage *string
}
