// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProviders = `-- name: CountProviders :one
SELECT COUNT(*)::int FROM providers
`

func (q *Queries) CountProviders(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countProviders)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteStaleProviders = `-- name: DeleteStaleProviders :many
DELETE FROM providers WHERE key NOT IN ('ECB', 'CURAPI') RETURNING key
`

func (q *Queries) DeleteStaleProviders(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteStaleProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchRatesForValidation = `-- name: FetchRatesForValidation :many
SELECT date, base, quote, rate, provider
FROM rates
WHERE ($1::text = '' OR date >= $1::date)
  AND ($2::text   = '' OR date <= $2::date)
  AND ($3::text = '' OR base = $3)
  AND ($4::text = '' OR quote = $4)
  AND provider = $5
ORDER BY date, provider, base, quote
LIMIT $6
`

type FetchRatesForValidationParams struct {
	DateFrom    string
	DateTo      string
	BaseCode    string
	QuoteCode   string
	ProviderKey string
	RowLimit    int32
}

func (q *Queries) FetchRatesForValidation(ctx context.Context, arg FetchRatesForValidationParams) ([]Rate, error) {
	rows, err := q.db.Query(ctx, fetchRatesForValidation,
		arg.DateFrom,
		arg.DateTo,
		arg.BaseCode,
		arg.QuoteCode,
		arg.ProviderKey,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rate
	for rows.Next() {
		var i Rate
		if err := rows.Scan(
			&i.Date,
			&i.Base,
			&i.Quote,
			&i.Rate,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLastSynced = `-- name: GetAllLastSynced :many
SELECT provider, MAX(date)::date AS last_synced
FROM rates
GROUP BY provider
`

type GetAllLastSyncedRow struct {
	Provider   string
	LastSynced pgtype.Date
}

func (q *Queries) GetAllLastSynced(ctx context.Context) ([]GetAllLastSyncedRow, error) {
	rows, err := q.db.Query(ctx, getAllLastSynced)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLastSyncedRow
	for rows.Next() {
		var i GetAllLastSyncedRow
		if err := rows.Scan(&i.Provider, &i.LastSynced); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrencyDateRange = `-- name: GetCurrencyDateRange :one
SELECT MIN(date)::date AS start_date, MAX(date)::date AS end_date
FROM rates
WHERE provider = $1 AND (quote = $2 OR base = $2)
`

type GetCurrencyDateRangeParams struct {
	Provider string
	Quote    string
}

type GetCurrencyDateRangeRow struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) GetCurrencyDateRange(ctx context.Context, arg GetCurrencyDateRangeParams) (GetCurrencyDateRangeRow, error) {
	row := q.db.QueryRow(ctx, getCurrencyDateRange, arg.Provider, arg.Quote)
	var i GetCurrencyDateRangeRow
	err := row.Scan(&i.StartDate, &i.EndDate)
	return i, err
}

const getLastSyncedForProvider = `-- name: GetLastSyncedForProvider :one
SELECT MAX(date)::date AS last_synced
FROM rates
WHERE provider = $1
`

func (q *Queries) GetLastSyncedForProvider(ctx context.Context, provider string) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getLastSyncedForProvider, provider)
	var last_synced pgtype.Date
	err := row.Scan(&last_synced)
	return last_synced, err
}

const listProviderKeys = `-- name: ListProviderKeys :many
SELECT key FROM providers ORDER BY key
`

func (q *Queries) ListProviderKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listProviderKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT key, name, country_code, rate_type, pivot_currency,
       data_url, terms_url, publish_time, publish_days, coverage_start
FROM providers
ORDER BY key
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.CountryCode,
			&i.RateType,
			&i.PivotCurrency,
			&i.DataUrl,
			&i.TermsUrl,
			&i.PublishTime,
			&i.PublishDays,
			&i.CoverageStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCurrency = `-- name: UpsertCurrency :exec
INSERT INTO currencies (iso_code, start_date, end_date)
VALUES ($1, $2, $3)
ON CONFLICT (iso_code) DO UPDATE SET
    start_date = LEAST(currencies.start_date, EXCLUDED.start_date),
    end_date   = GREATEST(currencies.end_date, EXCLUDED.end_date)
`

type UpsertCurrencyParams struct {
	IsoCode   string
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) UpsertCurrency(ctx context.Context, arg UpsertCurrencyParams) error {
	_, err := q.db.Exec(ctx, upsertCurrency, arg.IsoCode, arg.StartDate, arg.EndDate)
	return err
}

const upsertCurrencyCoverage = `-- name: UpsertCurrencyCoverage :exec
INSERT INTO currency_coverages (provider_key, iso_code, start_date, end_date)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider_key, iso_code) DO UPDATE SET
    start_date = LEAST(currency_coverages.start_date, EXCLUDED.start_date),
    end_date   = GREATEST(currency_coverages.end_date, EXCLUDED.end_date)
`

type UpsertCurrencyCoverageParams struct {
	ProviderKey string
	IsoCode     string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
}

func (q *Queries) UpsertCurrencyCoverage(ctx context.Context, arg UpsertCurrencyCoverageParams) error {
	_, err := q.db.Exec(ctx, upsertCurrencyCoverage,
		arg.ProviderKey,
		arg.IsoCode,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const upsertProvider = `-- name: UpsertProvider :exec
INSERT INTO providers (
    key, name, country_code, rate_type, pivot_currency,
    data_url, terms_url, publish_time, publish_days, coverage_start
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (key) DO UPDATE SET
    name           = EXCLUDED.name,
    country_code   = EXCLUDED.country_code,
    rate_type      = EXCLUDED.rate_type,
    pivot_currency = EXCLUDED.pivot_currency,
    data_url       = EXCLUDED.data_url,
    terms_url      = EXCLUDED.terms_url,
    publish_time   = EXCLUDED.publish_time,
    publish_days   = EXCLUDED.publish_days,
    coverage_start = EXCLUDED.coverage_start
`

type UpsertProviderParams struct {
	Key           string
	Name          string
	CountryCode   *string
	RateType      *string
	PivotCurrency *string
	DataUrl       *string
	TermsUrl      *string
	PublishTime   *int32
	PublishDays   *string
	CoverageStart pgtype.Date
}

func (q *Queries) UpsertProvider(ctx context.Context, arg UpsertProviderParams) error {
	_, err := q.db.Exec(ctx, upsertProvider,
		arg.Key,
		arg.Name,
		arg.CountryCode,
		arg.RateType,
		arg.PivotCurrency,
		arg.DataUrl,
		arg.TermsUrl,
		arg.PublishTime,
		arg.PublishDays,
		arg.CoverageStart,
	)
	return err
}
